[project]
name = "projeto-lp2-prova"
version = "0.1.0"
description = "Reconhecimento de cor de imagens de motos."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxruntime>=1.23.0",
    "opencv-python>=4.12.0.88",
    "rembg>=2.0.67",
]
